### PR TITLE
Morphing ID to public identity

### LINKED ISSUE #167: Morphing of ID to public identity number
In the current implementation, IDs abstracted away from the user and assigned by VirusTracker, is used to unqiuely identify each location and person. Based on the working assumption that Healthcare officials would possess their own way of uniquely identifying a person (e.g. NRIC in Singapore's context) and presumably locations as well, it is decided to morph the IDs into a public ID that is inputted by the user.

### PR DESCRIPTION
**Pull request by hopinxian**
This pull request aims to resolve #167 
Users are now required to input a unique identifier for all locations and persons inputted into the system. 

The following features come attached with the morphing of ID to a public unique identifier:
1. Add person and location commands now require an additional input of a unique identifier.
2. Delete location and person methods have been overloaded, allowing the user to either delete using index or unique identifier
3. Visits can be created by either referencing the index or unique identifier of the person and location involved. A mix of both is not allowed. 
4. Usage of IDs by other info handling functions have been checked for any breaking.
5. Adding via CSV has been morphed to ensure ids are required inside the CSV files.

This is currently a draft pull request.

### CODE REVIEW

**Comment by hopinxian** [comment]
Bugs found while morphing id:

1. Id was mistakenly treated as an index rather a unique identifier within GenerateLocationCommand and GeneratePersonCommand. The id of a person/location does not necessarily match the index of person/location in the complete person/locationbook. This bug would have surfaced when a person is deleted and a mismatch occurs.

**Comment by hopinxian** [comment]
This pull request is ready for merging.

**Comment by hopinxian** [comment]
While all effort has been made not to regress VirusTracker in this PR, because ID is used widely across all aspects of the VirusTracker, it is recommended that all teammates check through the tests and functionality in detail for any breaking of code or bugs.

**Review by siangernlow — APPROVED** [review]
LGTM

**Pull request merged**
